---
- hosts: node1.example.com
  tasks:
  - name: Check httpd installed
    yum:
      name: httpd
      state: present
  - name: Check httpd is running
    service:
      name: httpd 
      state: started
  - name: Create a file with content
    copy:
      dest: /var/www/html/index.html
      content: 'Welcome to my web server'
  - name: Check firewalld
    yum:
      name: firewalld
      state: present
  - name: Open 80
    firewalld:
      service: http
      permanent: true
      state: enabled
    notify:
    - Restart firewalld
  handlers:
   - name: Restart firewalld
     service:
       name: firewalld
       state: restarted
